apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "autonomously.fullname" . }}-config
  labels:
    {{- include "autonomously.labels" . | nindent 4 }}
data:
  RELEASE_NAME: {{ .Release.Name | quote }}
